basePath: /
consumes:
- application/json
info:
  description: |-
    Documentation for Product API

    Scheme: http
  title: of Product API
  version: 1.0.0
paths: {}
produces:
- application/json
swagger: "2.0"
